name: Terraform Run

on:
  push:
    branches:
    - main

jobs:

  job-Hello_World:
    runs-on: ubuntu-latest
    steps:
    - name: Hello World
      run : echo hello world

  job-Terraform_Apply:
    runs-on: ubuntu-latest
    steps:
    - name: CheckOut Repo
      uses: actions/checkout@v1
#
#    - name: Set Credentials
#      uses: aws-actions/configure-aws-credentials@v1
#      with:
#        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
#        aws-region: us-east-1
#
#    - name: Deploy objects to S3 bucket
#      run: |
#        aws s3 sync ./ s3://Bucket-Name \
#        --exclude '.git/*' \
#        --exclude '.github/*' \
#        --exclude 'README.md' \
#        --follow-symlinks \
#        --delete